config/routes.rb
Rails.application.routes.draw do
  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end

  root "todo_lists#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "users/confirm", to: "users#confirm"
  resources :users, param: :user_name, except: [:signup]
  get "/signup", to: "users#new"
  get "/login", to: "authentication#new"
  post "/auth/login", to: "authentication#login"
  get "/*a", to: "application#not_found"
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
	 before_action :authorize_request, except: %i[login new]

  def new 
  end

  # POST /auth/login
  def login
    @user = User.find_by(email_id: params[:email_id])
    if @user&.authenticate(params[:password])
      if @user.confirmed_at?
        token = JsonWebToken.encode(user_id: @user.id)
        time = Time.now + 24.hours.to_i
        render json: { token: token, exp: time.strftime("%m-%d-%Y %H:%M"),
                       email: @user.email_id }, status: :ok
      else
        render json: {error: 'Email not verified' }, status: :unauthorized
      end
    else
      render json: { error: 'unauthorized' }, status: :unauthorized
    end
  end

  private

  def login_params
    params.permit(:email_id, :password)
  end
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/views/authentication/new.html.erb
<h1> Log In </h1>
<%= form_with(url: auth_login_path) do |f| %>
 
<div class="form-group">
  <%= f.label :email_id %><br/>
  <%= f.email_field :email_id, class: "form-control" %>
</div>
 
<div class="form-group">
  <%= f.label :password %><br/>
  <%= f.password_field :password, class: "form-control" %>
</div>
 
<div class="form-group">
  <%= f.submit "Log in", class: "btn btn-primary" %>
</div>
 
<% end %>